### ISSUE TITLE
Deploy Maui

### ISSUE THREAD

**Issue by fisherab** [icatproject/ijp.torque#2]
```
Deploy Maui for better scheduling and ensure that machines with GPUs are correctly identified
and utilised. Also ensure that the memory requirements of a job are taken into account.
```

Original issue reported on code.google.com by `dr.s.m.fisher` on 2013-05-15 12:35:02

**Comment by brianritchie1312** [comment]
Closing this old issue; though we will have to consider improving job scheduling requirements in general.
