### ISSUE TITLE
Walltime limit needs increasing

### ISSUE THREAD

**Issue by fisherab** [icatproject/ijp.torque#3]
```
I had a number of quincy jobs running simultaneously and they were running very slowly.
Returning to check on them later I found that Torque had killed them off, providing
the error message: 

PBS: job killed: walltime 3610 exceeded limit 3600
```

Original issue reported on code.google.com by `kevin.phipps13` on 2013-05-15 15:55:31

**Comment by brianritchie1312** [comment]
Closing this as it is very old and I've never seen it happen. We have seen jobs simply disappear from Torque with no visible output, so this may resurface.
